-- MySQL Script generated by MySQL Workbench
-- Mon Dec 19 19:50:17 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema libweb5
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema libweb5
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `libweb5` DEFAULT CHARACTER SET utf8 ;
USE `libweb5` ;

-- -----------------------------------------------------
-- Table `libweb5`.`author`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libweb5`.`author` (
  `id_author` INT NOT NULL AUTO_INCREMENT,
  `author_name` VARCHAR(45) NULL,
  PRIMARY KEY (`id_author`),
  UNIQUE INDEX `id_author_UNIQUE` (`id_author` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `libweb5`.`publishing_house`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libweb5`.`publishing_house` (
  `id_publishing_house` INT NOT NULL AUTO_INCREMENT,
  `publishing_house_title` VARCHAR(45) NULL,
  PRIMARY KEY (`id_publishing_house`),
  UNIQUE INDEX `id_publishing_house_UNIQUE` (`id_publishing_house` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `libweb5`.`section`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libweb5`.`section` (
  `id_section` INT NOT NULL AUTO_INCREMENT,
  `section_title` VARCHAR(45) NULL,
  PRIMARY KEY (`id_section`),
  UNIQUE INDEX `id_section_UNIQUE` (`id_section` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `libweb5`.`book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libweb5`.`book` (
  `id_book` INT NOT NULL AUTO_INCREMENT,
  `book_title` VARCHAR(45) NULL,
  `book_description` VARCHAR(255) NULL,
  `book_id_section` INT NULL,
  `book_id_publishing_house` INT NULL,
  `book_id_author` INT NULL,
  `book_quantity` INT NULL,
  PRIMARY KEY (`id_book`),
  UNIQUE INDEX `id_book_UNIQUE` (`id_book` ASC) VISIBLE,
  INDEX `section_id_idx` (`book_id_section` ASC) VISIBLE,
  INDEX `publishing_house_id_idx` (`book_id_publishing_house` ASC) VISIBLE,
  INDEX `foreign_key_book_id_author_idx` (`book_id_author` ASC) VISIBLE,
  CONSTRAINT `foreign_key_book_id_publishing_house`
    FOREIGN KEY (`book_id_publishing_house`)
    REFERENCES `libweb5`.`publishing_house` (`id_publishing_house`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `foreign_key_book_id_section`
    FOREIGN KEY (`book_id_section`)
    REFERENCES `libweb5`.`section` (`id_section`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `foreign_key_book_id_author`
    FOREIGN KEY (`book_id_author`)
    REFERENCES `libweb5`.`author` (`id_author`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `libweb5`.`metro_station`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libweb5`.`metro_station` (
  `id_metro_station` INT NOT NULL AUTO_INCREMENT,
  `metro_station_title` VARCHAR(45) NULL,
  PRIMARY KEY (`id_metro_station`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `libweb5`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libweb5`.`user` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(45) NULL,
  `user_surname` VARCHAR(45) NULL,
  `user_patronymic` VARCHAR(45) NULL,
  `user_login` VARCHAR(45) NULL,
  `user_email` VARCHAR(45) NULL,
  `user_email_status` TINYINT NULL,
  `user_password` VARCHAR(45) NULL,
  `user_id_metro_station` INT NULL,
  PRIMARY KEY (`id_user`),
  UNIQUE INDEX `id_user_UNIQUE` (`id_user` ASC) VISIBLE,
  INDEX `foreign_key_user_id_metro_station_idx` (`user_id_metro_station` ASC) VISIBLE,
  CONSTRAINT `foreign_key_user_id_metro_station`
    FOREIGN KEY (`user_id_metro_station`)
    REFERENCES `libweb5`.`metro_station` (`id_metro_station`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `libweb5`.`book_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libweb5`.`book_user` (
  `id_book_user` INT NOT NULL AUTO_INCREMENT,
  `book_user_id_book` INT NULL,
  `book_user_id_user` INT NULL,
  `book_user_there_is` TINYINT NULL,
  `book_user_prise_of_loss` DECIMAL(5,0) NULL,
  PRIMARY KEY (`id_book_user`),
  INDEX `book_id_idx` (`book_user_id_book` ASC) VISIBLE,
  INDEX `user_id_idx` (`book_user_id_user` ASC) VISIBLE,
  CONSTRAINT `foreign_key_book_user_id_book`
    FOREIGN KEY (`book_user_id_book`)
    REFERENCES `libweb5`.`book` (`id_book`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `foreign_key_book_user_id_user`
    FOREIGN KEY (`book_user_id_user`)
    REFERENCES `libweb5`.`user` (`id_user`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `libweb5`.`extradition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libweb5`.`extradition` (
  `id_extradition` INT NOT NULL AUTO_INCREMENT,
  `extradition_id_book_user` INT NULL,
  `extradition_id_user` INT NULL,
  `extradition_date_of_extradition` DATE NULL,
  `extradition_required_return_date` DATE NULL,
  PRIMARY KEY (`id_extradition`),
  INDEX `book_user_id_idx` (`extradition_id_book_user` ASC) VISIBLE,
  INDEX `user_id_idx` (`extradition_id_user` ASC) VISIBLE,
  CONSTRAINT `foreign_key_extradition_id_book_user`
    FOREIGN KEY (`extradition_id_book_user`)
    REFERENCES `libweb5`.`book_user` (`id_book_user`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `foreign_key_extradition_id_user`
    FOREIGN KEY (`extradition_id_user`)
    REFERENCES `libweb5`.`user` (`id_user`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
